### ISSUE TITLE
fslint-gui does not seem to do anything on large file collections

### ISSUE THREAD

**Issue by COLABORATI** [pixelb/fslint#124] opened 2016-11-26 14:20 UTC
with some larger file collections (20GB and up) the gui, after clicking the find button, does seem to do absolutely nothing. It shows "searching..." but never seems to find anhything. 

There should be some kind of indicator about what is going on. 

The same is true for the findup tool - it just starts and does not produce any output.

BTW fdupes needs about 57 Minutes for that directory, however it still produces some progress indication.

Please implement some kind of progress indicator and also please test your software with lots of files - you would have seen this yourself if you would test with a big enough directory (and 20GB si not really big nowadays).

**Comment by pixelb** [comment] 2016-11-26 14:41
Duplicate of #17

**Closed by pixelb** 2016-11-26 14:41 UTC

**Comment by xekon** [comment] 2018-07-31 15:47
Thank you for this report, I tried fslint, and after waiting a couple hours on a 200gb directory of approximately 60k files, the only feedback I get from fslint is a spinning mouse cursor, indicating its doing something, a simple "im busy" type indicator is not good because many applications show those EVEN if they are hanging and not really working anymore.

Thanks to your comment I tried out fdupes, works like a charm :)
