### ISSUE TITLE
"select all but oldest" selects all for last group!

### ISSUE THREAD

**Issue by kaefert** [pixelb/fslint#121] opened 2016-03-19 22:18 UTC
"select all but oldest" selects all items in the last group, and when pressing delete it does not warn that that entire group is deleted.

Found this issue in Version 2.44-2 (Ubuntu 16.04 beta)

**Comment by pixelb** [comment] 2016-03-21 13:24
This is probably issue 94 fixed on trunk. That caused all items to be selected though. I couldn't reproduce after that fix

**Comment by riveravaldez** [comment] 2016-11-13 00:57
Quick question, in version 2.44-1: "Select all but oldest" → "Delete" → Nothing happens.
Should I open a bug on this?
Thanks, and sorry to ask this in here (couldn't find that bug).

**Comment by pixelb** [comment] 2016-11-13 02:01
Can you try with the latest trunk version? That should be as simple as:

    git clone https://github.com/pixelb/fslint.git
    cd fslint
    ./fslint-gui

**Comment by kaefert** [comment] 2017-02-20 08:17
Hi there. sorry for the long silence.
I tried what you suggested, and that version works perfect :)

But the fslint-gui version distributed with the newer ubuntu / linux mint distributions are horrible. First it "looks like" everything is selected, when you resize the window the selection is mostly correct, but the last group has both items selected.

**Comment by pixelb** [comment] 2017-02-20 18:05
A newer version has been released and is winding its way to ubuntu, so I can probably close this

**Closed by pixelb** 2017-02-20 18:05 UTC
